# Opposing arguments and objections {#sec-objections}

An [**opposing argument**](#opposing-arguments) is an argument whose conclusion is the opposite of another argument.  An **objection** is an argument whose conclusion is that (a) another argument has a false premise ([**challenging a premise**](#objecting-to-a-premise)), or (b) another argument's premises don't support its conclusion ([**challenging support**](#objecting-to-support)).  In other words, an opposing argument disagrees with a conclusion, while an objection disagrees with an argument.  We can represent both opposing arguments and objections in Mermaid, which enables us to represent complex debates. 


## Counterarguments

You might be more familiar with the terminology of *counterarguments* or *counters* in argumentative writing.  A counterargument is usually defined as something like ["An argument that is opposed to another argument"](https://en.wiktionary.org/wiki/counterargument).  This makes it a general term: opposing arguments, objections to premises, and objections to support are all counterarguments.  

Writing assignments that involve counterarguments often boil down to trading opposing arguments.  Consider [an example from a university writing center](https://www.unr.edu/writing-speaking-center/student-resources/writing-speaking-resources/counterarguments): 

> Admittedly, [many students would like to smoke on campus]{.red}. Some people may rightly argue that [if smoking on campus is not illegal, then it should be permitted]{.red}; however, [second-hand smoke may cause harm to those who have health issues like asthma, possibly putting them at risk]{.blue}.

We don't have a full essay to go along with this example, but it looks like the thesis of the full essay is "smoking should be banned on campus." The paragraph gives two independent opposing arguments (against the thesis), in red:

::: red
- Many students would like to smoke on campus.
- If smoking on campus is not illegal, then it should be permitted.
:::

Then we get an argument for the thesis, in blue: 

::: blue
- Second-hand smoke may cause harm to those who have health issues like asthma, possibly putting them at risk. 
:::

Trading opposing arguments like this might help us understand the main concerns motivating each side of the debate.  But it doesn't help us understand what each side thinks of the other side's arguments.  What does the pro-smoking side think about health concerns?  How would the anti-smoking side balance freedom and health?  

To go further, in this class (and many other philosophy classes), we emphasize objections and replies rather than opposing arguments.  


## Opposing arguments

Consider two arguments on the legality of abortion, one from the pro-choice side and one from the anti-abortion side.  In Mermaid, we'll use a regular arrow `-->` to indicate support for a claim (it gets colored blue in our custom theme) and a dashed arrow `-.->` to indicate opposition (it gets colored red).  We'll also label opposing arguments and objections with `O` rather than `P`, which will color their boxes red instead of blue in our custom theme.  

```{mermaid}
%%| echo: true
%%| code-folding: show
flowchart TB

Pautonomy(Everyone has a right to bodily autonomy)
Pautonomy --> C(Abortion should be legal)

Oright-to-life(An embryo has a right to life from conception)
Oright-to-life -.-> C
```

::: {.callout-note}
[*Embryo*](https://en.wikipedia.org/wiki/Embryo) is the term for the first 8-9 weeks of development, starting with conception (unification of an egg cell and sperm cell).  After that it's a [*fetus*](https://en.wikipedia.org/wiki/Embryo), though according to the Wikipedia article "Prenatal development is a continuum, with no clear defining feature distinguishing an embryo from a fetus."  *Length of pregnancy* is usually measured from the last menstrual period, which is typically 9-20 days before conception.  "Fetus" seems to be more common in the abortin debate than "embryo." But a six-week abortion ban is a prohibition on abortion during part of the embryonic stage.  So here I'm using "embryo." 
:::

These two arguments form a pair, each opposing the other.  They also don't engage with each other.  The pro-choice side appeals to the right to bodily autonomy, while the anti-abortion side appeals to the right to life.  But what does the pro-choice side think about the rights of a developing embryo?  And what does the anti-abortion side think about bodily autonomy?  Because they don't address each others' arguments, the debate doesn't go anywhere.  This makes opposing arguments not much better than *mere disagreement* (where one side makes a claim and the other side says the opposite, without any arguments).  

In contrast, objections help us understand what one side thinks of the other side's arguments.  This can lead to deeper insights:  What's the fundamental disagreement between the two sides?  Where do they agree?  Tracing out a complex debate, using tools like argument maps, might not resolve a controversy, but they can help us understand it better.  



## Objecting to a premise

Again, an **objection** is an argument whose conclusion is that (a) another argument has a false premise, or (b) another argument's premises don't support its conclusion. Let's start with the first kind of objection, which challenges a premise.  

A premise in an argument is just a claim, like any other, which means it can be supported or opposed with arguments.  In her 1973 article ["On the Moral and Legal Status of Abortion,"](https://drive.google.com/file/d/0B6oYmzobonqodjBuRTN5Qmdwb0E/view?usp=sharing&resourcekey=0-1WqVWQZio3z9oV4w8gsHyw) the ethicist Mary Anne Warren gave a critique of the pro-life claim that an embryo has a right to life from conception.  Here's my paraphrase of her critique:  

> An embryo lacks consciousness, the capacity to feel pain, self-motivated activity, the capacity to community, and self-awareness.  But only beings with these capacities have a right to life.  So an embryo does not have a right to life.  

This argument has two interdependent premises, so we'll collect them together using the argument label `Warren's objection`.  To color the argument label red, give it the type `OL` instead of `A`.  

```{mermaid}
%%| echo: true
%%| code-folding: show
flowchart TB

Pautonomy(Everyone has a right to bodily autonomy)
Pautonomy --> C(Abortion should be legal)

Oright-to-life(An embryo has a right to life from conception)
Oright-to-life -.-> C

OWarren1("Only beings with the capacity for 
     consciousness, the capacity to feel pain, 
     self-motivated activity, the capacity to 
     communicate, and self-awareness have 
     a right to life.")
OWarren2("An embryo lacks these capacities.")

OWarren1 & OWarren2 --- OL[Warren's objection] -.-> Oright-to-life
```

When you're reading this, remember that solid/blue indicates support and dashed/red indicates opposition.  So Warren's two premises support (solid blue line) her objection, and the objection opposes (dashed red line) the right-to-life premise.  In turn, the right-to-life premise opposes (dashed red line) the conclusion that abortion should be legal.  

A number of philosophers and other writers, including the [ethicist Don Marquis](https://drive.google.com/file/d/0B6oYmzobonqoWTJqeUhxSm5XcWM/view?usp=sharing&resourcekey=0-VNrlLS4h6Iz1txoiA9swGA), responded to Warren's argument by pointing out that coma patients have a right to life, despite lacking the capacities Warren points to. 

```{mermaid}
%%| echo: true
%%| code-folding: show
flowchart TB

Pautonomy(Everyone has a right to bodily autonomy)
Pautonomy --> C(Abortion should be legal)

Oright-to-life(An embryo has a right to life from conception)
Oright-to-life -.-> C

OWarren1("Only beings with the capacity for 
     consciousness, the capacity to feel pain, 
     self-motivated activity, the capacity to 
     communicate, and self-awareness have 
     a right to life.")
OWarren2("An embryo lacks these capacities.")

OWarren1 & OWarren2 --- OL[Warren's objection] -.-> Oright-to-life

OMarquis1("Coma patients also lack these capacities.")
OMarquis2("Coma patients have a right to life.")

OMarquis1 & OMarquis2 --- OLMarquis[Marquis' reply] -.-> OWarren1
```

Marquis' argument doesn't deny that an embryo lacks the capacities for consciousness, pain, and so on.  Instead he's criticizing Warren's claim that only beings with these capacities have a right to life.  So his argument is another example of an objection to a premise.  Specifically, this kind of objection to a previous objection is called a **reply**.  In philosophy classes, you'll often be asked to write papers where you present an argument, an objection, and finally a reply to that objection.  

Marquis didn't just give a reply to Warren's objection.  He offered his own argument for an embryo's right to life.  He calls it the "future-like-ours" argument, because it appeals to the idea that "The future of a standard fetus includes a set of experiences, projects, activities, and such which are identical with the futures of adult human beings and are identical with the futures of young children," and that a fetus has a right to life because it has the potential for this kind of future.  Marquis also argues that this "future-like-ours" view explains why temporary coma patients, at least, have a right to life: because they have the potential to awaken and lead a more-or-less typical adult human life.  

```{mermaid}
%%| echo: true
%%| code-folding: show
flowchart TB

Pautonomy(Everyone has a right to bodily autonomy)
Pautonomy --> C(Abortion should be legal)

Oright-to-life(An embryo has a right to life from conception)
Oright-to-life -.-> C

%% Warren's objection to the right-to-life argument
subgraph Warren's objection
OWarren1("Only beings with the capacity for 
     consciousness, the capacity to feel pain, 
     self-motivated activity, the capacity to 
     communicate, and self-awareness have 
     a right to life.")
OWarren2("An embryo lacks these capacities.")

OWarren1 & OWarren2 --- OL[Warren's objection] -.-> Oright-to-life
end


%% Marquis' reply to Warren's objection
subgraph Marquis' reply
OMarquis1("Coma patients also lack these capacities.")
OMarquis2("Coma patients have a right to life.")

OMarquis1 & OMarquis2 --- OLMarquis[Marquis' reply] -.-> OWarren1
end


%% Marquis' future-like-ours account of the right to life
subgraph Marquis' future-like-ours account
Pfuture("Any being with the potential to 
         lead a future-like-ours has a 
         right to life.")

Pcoma("Temporary coma patients have the potential
       to lead a future-like-ours.")
Pfuture & Pcoma --- Acoma[Marquis: Coma patient] --> OMarquis2

Pembryo("An embryo has the potential
		 to lead a future-like-ours.")
Pfuture & Pembryo --- Aembryo[Marquis: Embryo] --> Oright-to-life
end
```

::: {.callout-tip collapse=true}
## Adding boxes using subgraphs

You can draw a box around a section of the debate by putting `subgraph [name]` at the beginning of the section and `end` at the end.  Check the source code to see how.
:::

Initially, this map of the debate over abortion might not seem that helpful.  We've taken a complex moral and political debate and turned it into a complex diagram.  

But examining the map does help us understand a few aspects of the debate.  First, no one is denying that embryos lack the capacity to feel pain or consciousness or the like.  And no one is denying that (typically) embryos have the potential for a future-like-ours.  

Second, this debate has stepped back from the concrete issue of abortion itself, to focus on the abstract question *who has a right to life?*  The interlocutors give two very different answers to this question — Warren says a right to life requires certain cognitive capacities, Marquis says it's based on a "future-like-ours" — and there's no neutral way to determine which answer is right.  Abortion proponents have a strong incentive to favor Warren's account, and abortion opponents have an equally strong incentive to favor Marquis' account.  This is a common feature of philosophical debate, and in my opinion one reason people often find philosophy useless and frustrating.  

::: {.callout-note collapse=true}
## [interlocutor](https://en.wiktionary.org/wiki/interlocutor)

A person who takes part in dialogue or conversation. 
:::

But this abstract philosophical debate can still be useful, for helping us understand the deeper disagreement between abortion defenders and opponents.  This is the third point.  Anti-abortion advocates, like Marquis, often think of embryos and fetuses as (soon-to-be, more-or-less) infants.  They'll acknowledge that, in the early stages of pregnancy, an embryo or fetus is biologically pretty far off from a newborn.  But they emphasize what the embryo or fetus might be like, months or even years later.  Pro-choice advocates, like Warren, instead tend to focus on what the embryo or fetus is in itself at that early stage of development, setting aside what it might be like in the future.  When they do think about what the embryo might be in the future, they emphasize the effort and risk that pregnant people experience on the way.  

In her essay ["Virtue Theory and Abortion,"](https://drive.google.com/file/d/0B6oYmzobonqoZHBrNGpBcWx5aDQ/view?usp=sharing&resourcekey=0-MCEVK23t5bKtI2IGFVi41g) the ethicist Rosalind Hursthouse looks at this debate, and acknowledges that both of these perspectives on an embryo/fetus are important.  

> [T]he premature termination of a pregnancy is, in some sense, the cutting off of a new human life, and thereby ... connects with all our thoughts about human life and death, parenthood, and family relationships .... 
> 
> [But also, many women] view pregnancy only as eight months of misery, followed by hours if not days of agony and exhaustion, and abortion only as the blessed escape from this prospect[.  This point of view] is entirely understandable and does not manifest any lack of serious respect for human life or a shallow attitude to motherhood. (237, 240)

Hursthouse goes on to argue that an abstract debate over whether an embryo has a right to life is less useful than a concrete discussion of the many factors — financial, personal, cultural, medical — that play a role in whether someone chooses to carry a pregnancy to term or to have an abortion.  Rather than the high-profile pro-choice vs. anti-abortion positions, Hursthouse's view fits better with the [reproductive justice movement](https://en.wikipedia.org/wiki/Reproductive_justice), which advocates for legalized abortion but also the need for free, high-quality healthcare and childcare and living wages.  

::: {.exercises}
Consider this argument, which we met earlier in @sec-simple: 

> **Animal agriculture is not bad for the environment and it is not bad for people.** [The so-called scientific studies purporting to show that animals are bad for the environment have been repeatedly shown to be flawed.]{.red} [Ruminant animals, like cattle and sheep, are among the most sustainable food production systems on Earth, taking unusable land and waste products from vegetable and grain production, and turning it into healthy, nutrient-dense foods.]{.blue} Furthermore, [new scientific research is coming out showing that meat is extremely good for our health, and that a high-meat diet free of processed foods can actually reverse all kinds of chronic diseases.]{.purple} (Adapted from *Rulebook for Arguments*, Third Edition, pp36-37)

Using the rules from Chapter 1 of *Rulebook for Arguments*, develop an objection to one of the premises of this argument, and then a reply to your objection.  Present your objection and reply using an argument map.  
:::



## Objecting to support

The other way that we can object to an argument is to challenge the support relationship between premises and conclusion.  That is, we might accept all of an argument's premises, but still think that they don't give a good reason to accept the conclusion.  In the rest of this semester, we'll learn lots of different tools to assess support for different kinds of arguments.  For instance, when we talk about generalizations, or arguments by example, we'll introduce a rule that *generalizations need more than one example*.  A generalization with a single example can have a true premise — this thing did happen in this one particular case — but, because it violates the rule, it doesn't give much support to the conclusion.  

::: {.callout-note}
Students often have a lot of trouble with the idea of support.  It's okay if you don't get it at first.  Think of this course as teaching how to recognize how support works for different kinds of arguments.  
:::

To illustrate objecting to support, let's go back to our basic opposition between bodily autonomy and an embryo's right to life.  A pro-life person might agree that bodily autonomy — the right to do what you want with your own body — is important.  But, they might continue, not all rights are equally important.  Specifically, someone's right to life takes precedence over other rights.  As [a nineteenth-century aphorism](https://quoteinvestigator.com/2011/10/15/liberty-fist-nose/) put it, "My right to swing my fist ends where your nose begins."  

This objection challenges the pro-choice argument, but it doesn't challenge the premise of bodily autonomy.  Instead it challenges the support, the link, between that premise and the conclusion of legal abortion.  In Mermaid, we can represent this by opposing an argument label, rather than a premise.  So we'll add label for the pro-choice "autonomy argument," then the objection targeting it. 

```{mermaid}
%%| echo: true
flowchart TB

Pautonomy(Everyone has a right to bodily autonomy.)
Pautonomy --- Aautonomy[Autonomy arg.] --> C(Abortion should be legal.)

Oright-to-life(An embryo has a right to life from conception.) 
Oright-to-life -.-> C

Oprecedence("Someone's right to life takes precedence
			 over another person's right to bodily
			 autonomy.")
Oprecedence & Oright-to-life --- OL[Precedence obj.] -.-> Aautonomy
```

The premise that an embryo has a right to life is playing two roles in this debate.  First, on its own, it provides an argument that abortion should not be legal.  But also, when combined with the claim about the precedence of a right to life, it gives an objection to the autonomy argument.  If an embryo doesn't have a right to life, then it doesn't matter if a right to life takes precedence over bodily autonomy.  So someone might give a reply to the precedence objection in three ways:  

1. Challenge the premise that an embryo has a right to life. 
2. Challenge the premise that a right to life takes precedence over bodily autonomy. 
3. Challenge the support of the precedence objection.  

Warren's objection could be used to take strategy (1).  The ethicist Judith Jarvis Thomson took strategy (2) in her 1971 paper ["A Defense of Abortion"](https://drive.google.com/file/d/0B6oYmzobonqoR2Fka0FJbjZYMzQ/view?usp=sharing&resourcekey=0-sKH9_nhlpTXfCizCcVQBiA). 

::: {.callout-note collapse=true}
## Thomson's defense of abortion

In her paper, Thomson grants (at least for the sake of argument) that an embryo has a right to life.  She defense of abortion is to argue that this right to life does not take precedence over bodily autonomy.  She introduces a famous thought experiment, in which you're kidnapped and surgically connected to a world-famous violinist, who's in a coma and will die if you don't act as his life support system for the next nine months.  The violinist has a right to life, she says, but *not* a right to the use of your body.  

In my opinion, Thomson's argument is based on an excessively strong form of individualism.  Later in the paper, in another thought experiment, she imagines that she's dying in bed, and the actor Henry Fonda is standing in the doorway of her room, just a few feet away.  If Fonda walks over and touches her forehead, she'll be instantly cured of her disease and her life will be saved.  She writes: 

> Suppose he has only to walk across the room, place a hand briefly on my brow-and lo, my life is saved. Then surely he ought to do it, it would be indecent to refuse. Is it to be said "Ah,well, it follows that in this case she has a right to the touch of his hand on her brow, and so it would be an injustice in him to refuse"? ... It's rather a shocking idea that anyone's rights should fade away and disappear as it gets harder and harder to accord them to him. (61)

In other words, Thomson says that Fonda *morally should* do this trivial thing to save her life.  But she has no moral (or legal) *right* to demand that he does so.  

My objection is that Thomson's view would undermine any use of taxpayer funds to provide social benefits:  public roads, education, clean air and water, shelter, health care, food, and so on.  There are people who will die today because of lack of access to shelter or health care.  Does justice require that wealthy people be taxed, and those funds use to pay for things like homeless shelters and universal health insurance?  I think it does.  In other words, vulnerable people do have a *right* to demand that wealthy people pay for these kinds of things.  
:::

The third strategy amounts to saying:  Okay, at least for the sake of argument, I'll agree that an embryo has a right to life; and a right to life takes precedence over a right to bodily autonomy.  But *even then* the precedence objection doesn't work.  Those premises aren't enough to conclude that the bodily autonomy argument is flawed.  

One way to take this third strategy is to make a distinction between killing someone and letting them die.  Many people would say there's a difference between letting a young child drown in a bathtub and actively holding them underwater until they drown.  One version of this distinction is in terms of intentions: if the child managed to save themselves, you wouldn't reach down and push them back under.  Someone might go on to argue that letting someone die doesn't violate their right to life — it was sort of an accident or unintended consequence — and that abortion is letting an embryo die — if the embryo someone managed to survive the procedure, you wouldn't actively try to kill it.  

::: {.callout-note}
The drowning children example comes from a paper by the ethicist James Rachels.  Rachels' point was to challenge the distinction: he claims that there's actually no morally significant difference between these two cases.  
:::

This reply to the precedence objection again targets the support of the argument.  The objection can agree that the right to life takes precedence over bodily autonomy.  But, they claim, the right to life isn't violated in abortion, because abortion is letting an embryo die rather than killing it.  

```{mermaid}
%%| echo: true
flowchart TB

Pautonomy(Everyone has a right to bodily autonomy.)
Pautonomy --- Aautonomy[Autonomy arg.] --> C(Abortion should be legal.)

Oright-to-life(An embryo has a right to life from conception.) 
Oright-to-life -.-> C

Oprecedence("Someone's right to life takes precedence
			 over another person's right to bodily
			 autonomy.")
Oprecedence & Oright-to-life --- OLprecedence[Precedence obj.] -.-> Aautonomy

Okilling-die("Unlike killing, letting someone die 
              does not violate their right to life.")
Oabortion-die("Abortion is letting an embryo die, 
               not killing it")
Okilling-die & Oabortion-die --- OL[Killing vs.\nletting die] -.-> OLprecedence
```

While this is a useful example for showing how we represent objections and replies in argument maps, I don't think it's a very compelling reply to the objection.  In my opinion, both premises have problems.  First, many homeless people in our society die of exposure and treatable diseases.  This is letting them die — we don't actively hunt down homeless people who survive these challenges — but denying them access to housing and health care does, I think, violate their right to life.  Second, it's not clear to me what the difference is supposed to be between ending a pregnancy and ending the life of the embryo or fetus involved in that pregnancy, i.e., killing it.  It seems to me like these are just two ways of describing the same action.  

::: {.exercises}
Expand the argument map above to include my two objections to the killing vs. letting die reply. Are these objections to support or objections to premises? 
:::


