project:
  type: book
  output-dir: docs

book:
  title: "Mapping Arguments and Debates with Argdown"
  author: "Dan Hicks"
  chapters:
    - index.md
    - 02-argdown.md
    - 03-simple.md
    - 04-interdependent.md
    - 05-objections.md
    - 06-biofuels.md
  repo-url: https://github.com/dhicks/argmaps

format:
  html:
    theme: 
        - cosmo
        - theming.scss

filters:
    - argdown-filter

number-sections: true

