project:
  type: book
  output-dir: docs

book:
  title: "Mapping Arguments and Debates with Mermaid"
  author: "Dan Hicks"
  chapters:
    - index.qmd
    - 02-mermaid.qmd
    - 03-simple.qmd
    - 04-interdependent.qmd
    - 05-objections.qmd
    - 06-biofuels.qmd
  repo-url: https://github.com/dhicks/argmaps
  resources:
    - CNAME

format:
  html:
    theme: 
        - cosmo
        - mermaid.css
        - theming.scss
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    
execute:
    echo: true

number-sections: true

